export const allowedGifts = new Set([
"rose",
"tiktok",
"gg",
"you're awesome",
"fluffy heart",
"cake slice",
"pop",
"wink wink",
"ice cream cone",
"love you so much",
"oldies",
"freestyle",
"glow stick",
"heart me",
"so cute",
"fire",
"thumbs up",
"heart",
"love you",
"bibingka",
"fest pop",
"music album",
"go popular",
"club cheers",
"wink charm",
"team bracelet",
"finger heart",
"overreact",
"name shoutout",
"super popular",
"cheer you up",
"club power",
"rosa",
"friendship necklace",
"slow motion",
"journey pass",
"lucky pony",
"league ball",
"chocolate",
"i love you",
"fried chicken",
"style me up",
"heart gaze",
"bravo!",
"next legends",
"perfume",
"doughnut",
"paper crane",
"little crown",
"cap",
"hat and mustache",
"like-pop",
"love painting",
"bubble gum",
"mark of love",
"sundae bowl",
"charmer bow",
"club victory",
"level-up sparks",
"greeting heart",
"game controller",
"super gg",
"mishka bear",
"confetti",
"hand hearts",
"hand heart",
"ko!",
"marvelous confetti",
"singing magic",
"bowknot",
"big shout out",
"chatting popcorn",
"masquerade",
"balloon crown",
"feather tiara",
"caterpillar chaos",
"catrina",
"raving snail",
"santa cocoa",
"love glasses",
"song of harvest",
"league countdown",
"sunglasses",
"hearts",
"garland headpiece",
"cheer for you",
"stinging bee",
"massage for you",
"coffee magic",
"cheering crab",
"night star",
"twinkling star",
"blow bubbles",
"floating octopus",
"flower headband",
"bowtiful crown",
"sour buddy",
"rose hand",
"melon juice",
"coconut juice",
"chirpy kisses",
"joker ball",
"heart hood",
"balloons",
"magic genie",
"rose bear",
"cat",
"pinch face",
"candy bouquet",
"ice cream mic",
"star goggles",
"cheer mic",
"music bubbles",
"palm breeze",
"forest elf",
"face-pulling",
"treasured voice",
"melodic birds",
"surfing penguin",
"party blossom",
"dreamy strings",
"sweet flutter",
"live ranking crown",
"boxing gloves",
"corgi",
"fruit friends",
"naughty chicken",
"play for you",
"rock star",
"butterfly for you",
"falling for you",
"puppy kisses",
"spider on web",
"united heart",
"kicker challenge",
"hi! rosie!",
"go hamster",
"bat headwear",
"melody glasses",
"penguin snowpal",
"judy pose",
"music mate",
"llama greetings",
"love call",
"budding heart",
"feather mask",
"backing monkey",
"become kitten",
"marked with love",
"vinyl flip",
"juicy cap",
"batwing hat",
"mystic drink",
"beach maracas",
"vintage flight",
"gingerbread man",
"rocking shroom",
"forever rosa",
"magic rhythm",
"relaxed goose",
"tom's hug",
"rosie the rose bean",
"jollie the joy bean",
"rocky the rock bean",
"sage the smart bean",
"sage's slash",
"let butterfly dances",
"kitten kneading",
"shoot the apple",
"alien buddy",
"rosie's concert",
"you are loved",
"tiger lift",
"santa owl surprise",
"confetti bear",
"singing sax",
"fairy locket",
"panda snap",
"crystal dreams",
"wishing cake",
"mic champ",
"bounce speakers",
"reindeer milk",
"beating heart",
"encore clap",
"pirate's treasure",
"candy loot",
"captured vocals",
"batting cutie",
"space love",
"xmas tree hat",
"powerful mind",
"hat of joy",
"halloween fun hat",
"music conductor",
"celebration hat",
"city pop",
"cupid koala",
"coral",
"im just a hamster",
"rose soundwave",
"hands up",
"money gun",
"you’re amazing",
"vr goggles",
"dj glasses",
"tricycle",
"manifesting",
"dragon crown",
"star map polaris",
"racing helmet",
"xxxl flowers",
"prince",
"bunny crown",
"magic prop",
"roses",
"cozy xmas set",
"mystery box",
"heart guitar",
"smitten kitten",
"mighty sweetie",
"gem gun",
"bubbly kiss",
"fully bloomed sakura",
"league trophy",
"rookie king",
"join butterflies",
"colorful wings",
"the van cat",
"love flight",
"train",
"sakura crown",
"travel with you",
"lucky airdrop box",
"grand show",
"puyo shuffle!",
"trending figure",
"watermelon love",
"blooming ribbons",
"galaxy",
"giraffe",
"fairy wings",
"flamingo groove",
"shiny air balloon",
"sparkle dance",
"joy floats",
"candy puffs",
"fireworks",
"diamond tree",
"magic role",
"arcade game",
"umbrella of love",
"autumn picnic",
"vibrant stage",
"level ship",
"chasing the dream",
"lover’s lock",
"greeting card",
"future encounter",
"under control",
"cherry blossoms",
"racing debut",
"you're so fly",
"astrobear",
"a treat for my lion",
"valentine cake",
"blooming heart",
"here we go",
"love drop",
"jeepney",
"fox legend",
"doll new year greeting",
"star of red carpet",
"cooper flies home",
"mystery firework",
"sky drift",
"whale diving",
"blow rosie kisses",
"jollie's heartland",
"rocky's punch",
"sage's coinbot",
"stargazing",
"by the glaziers",
"animal band",
"samfaring tom",
"motorcycle",
"ring of honor-cube",
"rhythmic bear",
"party bus",
"level-up spotlight",
"meteor shower",
"look up",
"dream big",
"magic world",
"your concert",
"private jet",
"leon the kitten",
"fiery dragon",
"signature jet",
"sugar whiskers",
"sage’s venture",
"league fandom",
"unicorn fantasy",
"flying jets",
"fluffy buddies",
"cub on clouds",
"valiant odyssey",
"devoted heart",
"future city",
"sam in new city",
"work hard play harder",
"strong finish",
"forevermore",
"romance blossoms",
"lili the leopard",
"celebration time",
"happy party",
"sports car",
"majestic hearts",
"star throne",
"leon and lili",
"interstellar",
"sunset speedway",
"falcon",
"red lightning",
"level-up spectacle",
"invincible hammer",
"crystal heart",
"paris",
"lny horse",
"philippine eagle",
"rosa nebula",
"future journey",
"gaming console",
"party on&on",
"romance the world",
"amusement park",
"fly love",
"tiktok shuttle",
"premium shuttle",
"infinite heart",
"phoenix",
"adam’s dream",
"cyber roar",
"dragon flame",
"lion",
"leon and lion",
"tiktok universe+",
"tiktok stars",
"thunder falcon",
"fire phoenix",
"pegasus",
"julius the champion",
"tiktok universe"
]);
